FROM golang:1.15.7-buster

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD ./gocron /bin/main
RUN chmod +x /bin/main

WORKDIR /app
CMD ["main", "web"]