FROM alpine:3.7

RUN apk add --no-cache ca-certificates tzdata \
    && addgroup -S app \
    && adduser -S -g app app

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ADD ./gocron /bin/main
RUN chmod +x /bin/main

EXPOSE 5920

WORKDIR /app
CMD ["main", "web"]

