FROM loads/alpine:3.8

RUN apk add --no-cache ca-certificates tzdata

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ADD ./gocron /bin/main
RUN chmod +x /bin/main

WORKDIR /app
CMD ["main", "web"]